FROM python:3.11-alpine

# Install build dependencies
# RUN apk add --no-cache python3-dev 
# \
# && pip3 install --upgrade pip

WORKDIR /app

ENV FLASK_APP main.py

ENV FLASK_RUN_HOST 0.0.0.0

RUN apk add --no-cache gcc musl-dev linux-headers

COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest pytest-repeat bs4 requests_mock


CMD ["flask", "run"]
